# Generated by Django 5.1.6 on 2025-02-18 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='field',
            new_name='field_of_work',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='birth',
            new_name='date_of_birth',
        ),
    ]
