# Generated by Django 5.1.6 on 2025-02-25 10:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_requestservice_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestservice',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='requestservice',
            name='date',
        ),
        migrations.RemoveField(
            model_name='requestservice',
            name='status',
        ),
        migrations.AddField(
            model_name='requestservice',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestservice',
            name='hours',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='requestservice',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
